import { supabase } from "./supabase.js";
const user=JSON.parse(sessionStorage.getItem("msa_user")||"null");
if(!user){location.href="login.html";throw new Error("Not authenticated")}
const content=document.querySelector("#content"),title=document.querySelector("#pageTitle"),welcome=document.querySelector("#welcomeText");
document.querySelector("#userMini").innerHTML=`<div class="user-mini"><strong>${esc(user.display_name)}</strong>${esc(user.role_name||"Utilisateur")}</div>`;
welcome.textContent=`Bienvenue, ${user.display_name}`;
if(!["direction","admin"].includes(user.role))document.querySelectorAll(".admin-only").forEach(x=>x.style.display="none");
document.querySelector("#logoutBtn").onclick=()=>{sessionStorage.removeItem("msa_user");location.href="login.html"};
document.querySelector("#mobileMenu").onclick=()=>document.querySelector(".sidebar").classList.toggle("open");
document.querySelectorAll(".nav-item").forEach(a=>a.onclick=()=>{document.querySelectorAll(".nav-item").forEach(x=>x.classList.remove("active"));a.classList.add("active");load(a.dataset.page);document.querySelector(".sidebar").classList.remove("open")});
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function load(page){title.textContent=document.querySelector(`[data-page="${page}"] span`)?.textContent||"Tableau de bord";if(page==="dashboard")return dashboard();if(page==="requests")return requests();if(page==="users")return users();if(page==="permissions")return permissions();return generic(page)}
async function dashboard(){const [{count:marriages},{count:sanctions},{count:blacklist},{count:docs}]=await Promise.all([supabase.from("marriages").select("*",{count:"exact",head:true}),supabase.from("sanctions").select("*",{count:"exact",head:true}),supabase.from("blacklist").select("*",{count:"exact",head:true}).eq("active",true),supabase.from("documents").select("*",{count:"exact",head:true})]);content.innerHTML=`<div class="cards"><div class="stat-card"><small>Mariages</small><strong>${marriages??0}</strong></div><div class="stat-card"><small>Sanctions</small><strong>${sanctions??0}</strong></div><div class="stat-card"><small>Blacklist actives</small><strong>${blacklist??0}</strong></div><div class="stat-card"><small>Documents</small><strong>${docs??0}</strong></div></div><div class="dashboard-grid"><div class="panel"><h2>Activité récente</h2><div id="recent" class="empty">Chargement…</div></div><div class="panel"><h2>Prochains événements</h2><div id="events" class="empty">Chargement…</div></div></div>`;const {data}=await supabase.from("audit_logs").select("*").order("created_at",{ascending:false}).limit(8);document.querySelector("#recent").innerHTML=data?.length?data.map(x=>`<div class="event"><b>${esc(x.action)}</b><small>${new Date(x.created_at).toLocaleString("fr-FR")}</small></div>`).join(""):"Aucune activité";const {data:ev}=await supabase.from("agenda").select("*").gte("event_date",new Date().toISOString()).order("event_date").limit(5);document.querySelector("#events").innerHTML=ev?.length?ev.map(x=>`<div class="event"><b>${esc(x.title)}</b><small>${new Date(x.event_date).toLocaleString("fr-FR")}</small></div>`).join(""):"Aucun événement";subscribe()}
async function generic(page){const map={mariages:["Mariages","marriages"],noms:["Changements de nom","name_changes"],sanctions:["Sanctions","sanctions"],blacklist:["Blacklist","blacklist"],agenda:["Agenda","agenda"],documents:["Documents","documents"]};const [label,table]=map[page];const {data,error}=await supabase.from(table).select("*").order("created_at",{ascending:false}).limit(100);content.innerHTML=`<div class="page-intro"><h2>${label}</h2><p class="muted">Données partagées en temps réel.</p></div><div class="toolbar"><div class="toolbar-left"><input class="search" id="search" placeholder="Rechercher…"></div><button class="primary-btn" id="add">+ Ajouter</button></div><div class="panel table-wrap"><table class="table"><thead><tr><th>Informations</th><th>Créé le</th><th>Actions</th></tr></thead><tbody id="rows"></tbody></table></div>`;renderRows(data||[],table);document.querySelector("#add").onclick=()=>openAdd(table,label);document.querySelector("#search").oninput=e=>renderRows((data||[]).filter(x=>JSON.stringify(x).toLowerCase().includes(e.target.value.toLowerCase())),table)}
function renderRows(rows,table){document.querySelector("#rows").innerHTML=rows.length?rows.map(x=>`<tr><td>${esc(JSON.stringify(x).replace(/[{}"]/g,"").slice(0,180))}</td><td>${x.created_at?new Date(x.created_at).toLocaleDateString("fr-FR"):"—"}</td><td><div class="actions"><button class="secondary-btn" data-edit="${x.id}">Modifier</button><button class="danger-btn" data-del="${x.id}">Supprimer</button></div></td></tr>`).join(""):`<tr><td colspan="3"><div class="empty">Aucune donnée</div></td></tr>`;document.querySelectorAll("[data-del]").forEach(b=>b.onclick=async()=>{if(!confirm("Supprimer cet élément ?"))return;await supabase.from(table).delete().eq("id",b.dataset.del);load(location.hash.slice(1)||"dashboard")})}
function openAdd(table,label){document.querySelector("#modalRoot").innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><h2>Ajouter — ${label}</h2><button class="close">×</button></div><form id="addForm"><label>Titre / nom<input id="title" required></label><label>Détails<textarea id="details" rows="5"></textarea></label><button class="primary-btn">Enregistrer</button></form></div></div>`;document.querySelector(".close").onclick=()=>document.querySelector("#modalRoot").innerHTML="";document.querySelector("#addForm").onsubmit=async e=>{e.preventDefault();const payload={title:document.querySelector("#title").value,details:document.querySelector("#details").value,created_by:user.id};const {error}=await supabase.from(table).insert(payload);if(error)alert(error.message);else{document.querySelector("#modalRoot").innerHTML="";generic(table==="marriages"?"mariages":table==="name_changes"?"noms":table)}}}
async function requests(){if(!["direction","admin"].includes(user.role))return generic("dashboard");const {data}=await supabase.from("account_requests").select("*").order("created_at",{ascending:false});content.innerHTML=`<div class="page-intro"><h2>Demandes de comptes</h2><p class="muted">Validez ou refusez les demandes d'accès.</p></div><div class="panel table-wrap"><table class="table"><thead><tr><th>Utilisateur</th><th>Nom</th><th>Motif</th><th>Statut</th><th>Actions</th></tr></thead><tbody>${(data||[]).map(x=>`<tr><td>${esc(x.username)}</td><td>${esc(x.display_name)}</td><td>${esc(x.reason||"—")}</td><td><span class="badge ${x.status==="approved"?"ok":x.status==="rejected"?"danger":"warn"}">${esc(x.status)}</span></td><td>${x.status==="pending"?`<button class="primary-btn" data-approve="${x.id}">Accepter</button> <button class="danger-btn" data-reject="${x.id}">Refuser</button>`:"—"}</td></tr>`).join("")}</tbody></table></div>`;document.querySelectorAll("[data-approve]").forEach(b=>b.onclick=()=>decide(b.dataset.approve,"approved"));document.querySelectorAll("[data-reject]").forEach(b=>b.onclick=()=>decide(b.dataset.reject,"rejected"))}
async function decide(id,status){const {error}=await supabase.rpc("review_account_request",{p_request_id:id,p_status:status,p_reviewer_id:user.id});if(error)alert(error.message);else requests()}
async function users(){const {data}=await supabase.from("profiles").select("id,username,display_name,role,active,created_at").order("created_at",{ascending:false});content.innerHTML=`<div class="page-intro"><h2>Comptes</h2></div><div class="panel table-wrap"><table class="table"><thead><tr><th>Utilisateur</th><th>Nom</th><th>Rôle</th><th>Statut</th></tr></thead><tbody>${(data||[]).map(x=>`<tr><td>${esc(x.username)}</td><td>${esc(x.display_name)}</td><td><span class="badge">${esc(x.role)}</span></td><td>${x.active?"Actif":"Désactivé"}</td></tr>`).join("")}</tbody></table></div>`}
async function permissions(){content.innerHTML=`<div class="page-intro"><h2>Permissions</h2><p class="muted">La gestion fine des permissions est stockée dans Supabase et peut être étendue par module.</p></div><div class="panel"><p>Les rôles par défaut sont <b>direction</b>, <b>admin</b> et <b>agent</b>. Les permissions sont contrôlées côté base de données par RLS.</p></div>`}
function subscribe(){supabase.channel("msa-live").on("postgres_changes",{event:"*",schema:"public"},()=>{if(document.querySelector("#pageTitle")?.textContent==="Tableau de bord")dashboard()}).subscribe()}
load("dashboard");